// ============================================================
// PROFESSOR AUTO-SELECTOR — by period code
// Fixed console helper
// Data source: click-data.json
// Usage:
//   await loadClickData();
//   await selectProfessors('T3');
//   await selectProfessors('T3', 'TER');
//   await run();
//   await run('T3', 'TER');
// ============================================================

let clickData = null;
let runCursor = 0;

const dayOrder = ['SEG', 'TER', 'QUA', 'QUI', 'SEX'];

const dayAliases = {
    SEG: 'SEG',
    SEGUNDA: 'SEG',
    'SEGUNDA-FEIRA': 'SEG',
    TER: 'TER',
    TERCA: 'TER',
    'TERCA-FEIRA': 'TER',
    TERÇA: 'TER',
    'TERÇA-FEIRA': 'TER',
    QUA: 'QUA',
    QUARTA: 'QUA',
    'QUARTA-FEIRA': 'QUA',
    QUI: 'QUI',
    QUINTA: 'QUI',
    'QUINTA-FEIRA': 'QUI',
    SEX: 'SEX',
    SEXTA: 'SEX',
    'SEXTA-FEIRA': 'SEX'
};

function normalizeText(value) {
    return String(value || '')
        .normalize('NFD')
        .replace(/[̀-ͯ]/g, '')
        .toUpperCase()
        .trim();
}

function normalizePeriod(periodCode) {
    return normalizeText(periodCode);
}

function normalizeDay(dayCode) {
    return dayAliases[normalizeText(dayCode)] || null;
}

function validateClickData(data) {
    if (!data || typeof data !== 'object') {
        throw new Error('Invalid click data file.');
    }

    const requiredKeys = ['periodTimes', 'professorsByPeriod', 'scheduleByDayAndPeriod'];
    for (const key of requiredKeys) {
        if (!data[key] || typeof data[key] !== 'object') {
            throw new Error('Invalid click data file: missing ' + key);
        }
    }

    return data;
}

async function pickClickDataFile() {
    if (typeof window.showOpenFilePicker === 'function') {
        const [handle] = await window.showOpenFilePicker({
            multiple: false,
            types: [{
                description: 'JSON data',
                accept: { 'application/json': ['.json'] }
            }]
        });
        const file = await handle.getFile();
        return { name: file.name, text: await file.text() };
    }

    return new Promise((resolve, reject) => {
        const input = document.createElement('input');
        input.type = 'file';
        input.accept = '.json,application/json';
        input.style.display = 'none';
        input.addEventListener('change', async event => {
            const file = event.target.files && event.target.files[0];
            if (!file) {
                reject(new Error('No file selected.'));
                return;
            }

            resolve({ name: file.name, text: await file.text() });
        }, { once: true });
        document.body.appendChild(input);
        input.click();
        setTimeout(() => input.remove(), 0);
    });
}

async function loadClickData(source) {
    if (source && typeof source === 'object' && !Array.isArray(source)) {
        clickData = validateClickData(source);
        console.log('Click data loaded from object.');
        return clickData;
    }

    if (typeof source === 'string' && source.trim().startsWith('{')) {
        clickData = validateClickData(JSON.parse(source));
        console.log('Click data loaded from JSON text.');
        return clickData;
    }

    const filePayload = await pickClickDataFile();
    clickData = validateClickData(JSON.parse(filePayload.text));
    console.log('Click data loaded from ' + filePayload.name + '.');
    console.log('Available periods: ' + Object.keys(clickData.periodTimes).join(', '));
    return clickData;
}

function getClickData() {
    if (!clickData) {
        throw new Error('Click data not loaded. Run await loadClickData() and choose click-data.json generated by build.sh.');
    }

    return clickData;
}

function simulateClick(element) {
    ['pointerdown', 'mousedown', 'pointerup', 'mouseup', 'click'].forEach(eventType => {
        element.dispatchEvent(new MouseEvent(eventType, {
            bubbles: true, cancelable: true, view: window, button: 0
        }));
    });
}

function resolveExplicitTable(explicitTable) {
    if (!explicitTable) {
        return null;
    }

    if (typeof explicitTable === 'string') {
        return document.querySelector(explicitTable);
    }

    return explicitTable;
}

function isVisibleElement(element) {
    if (!element) {
        return false;
    }

    const style = window.getComputedStyle(element);
    return style.display !== 'none' && style.visibility !== 'hidden';
}

function getTableRowCount(table) {
    return table.querySelectorAll('tbody tr.rec').length;
}

function getProfessorTableHeaders(table) {
    const container = table.closest('.dt-container');
    const headerSource = container ? container.querySelector('thead') : table.querySelector('thead');
    return normalizeText(headerSource ? headerSource.textContent : '');
}

function getVisibleTable(explicitTable) {
    const resolvedExplicitTable = resolveExplicitTable(explicitTable);
    if (resolvedExplicitTable) {
        return resolvedExplicitTable;
    }

    const visibleTables = Array.from(document.querySelectorAll('.asc-dt'))
        .filter(isVisibleElement);
    const rowTables = visibleTables.filter(table => getTableRowCount(table) > 0);
    const professorTables = rowTables.filter(table => {
        const headerText = getProfessorTableHeaders(table);
        return headerText.includes('ABREVIACAO')
            && headerText.includes('ULTIMO NOME')
            && headerText.includes('PRIMEIRO NOME');
    });

    if (professorTables.length > 0) {
        return professorTables
            .sort((tableA, tableB) => getTableRowCount(tableB) - getTableRowCount(tableA))[0];
    }

    return rowTables[0] || null;
}

function getRowSearchValues(row) {
    const cells = row.querySelectorAll('td');
    return [1, 2, 3]
        .map(index => normalizeText(cells[index] ? cells[index].textContent : ''))
        .filter(Boolean);
}

function getProfessorNamesForSelection(periodCode, dayCode) {
    const data = getClickData();
    const normalizedPeriod = normalizePeriod(periodCode);
    if (!data.periodTimes[normalizedPeriod]) {
        throw new Error('Unknown period: ' + periodCode);
    }

    const normalizedDay = dayCode ? normalizeDay(dayCode) : null;
    if (dayCode && !normalizedDay) {
        throw new Error('Unknown day: ' + dayCode);
    }

    if (normalizedDay) {
        return data.scheduleByDayAndPeriod[normalizedDay] && data.scheduleByDayAndPeriod[normalizedDay][normalizedPeriod]
            ? data.scheduleByDayAndPeriod[normalizedDay][normalizedPeriod]
            : [];
    }

    const daysWithEntries = Object.entries(data.scheduleByDayAndPeriod)
        .filter(([, periods]) => Array.isArray(periods[normalizedPeriod]) && periods[normalizedPeriod].length > 0)
        .map(([day]) => day);

    if (daysWithEntries.length > 1) {
        console.warn('Period ' + normalizedPeriod + ' appears on ' + daysWithEntries.join(', ') + '. Using union of professors across days. Pass a day code as the second argument for exact selection.');
    }

    return data.professorsByPeriod[normalizedPeriod] || [];
}

function getRunQueue() {
    const data = getClickData();
    const queue = [];
    const periodOrder = Object.keys(data.periodTimes);

    for (const day of dayOrder) {
        const periodsForDay = data.scheduleByDayAndPeriod[day] || {};

        for (const period of periodOrder) {
            const professors = periodsForDay[period];
            if (Array.isArray(professors) && professors.length > 0) {
                queue.push({ day, period });
            }
        }
    }

    return queue;
}

function formatRunLabel(periodCode, dayCode) {
    return dayCode ? dayCode + ' ' + periodCode : periodCode;
}

async function selectProfessors(periodCode, dayCode, explicitTable) {
    const table = getVisibleTable(explicitTable);
    if (!table) {
        throw new Error('No visible professor selection table found. Open the Mais professores dialog before running selectProfessors().');
    }

    const professorNames = getProfessorNamesForSelection(periodCode, dayCode);
    const selectionLabel = (dayCode ? dayCode + ' ' : '') + periodCode;

    if (professorNames.length === 0) {
        console.warn('No professors configured for ' + selectionLabel + '.');
        return { found: 0, notFound: [], selected: [] };
    }

    const rows = Array.from(table.querySelectorAll('tbody tr.rec'));
    let found = 0;
    const notFound = [];

    for (const name of professorNames) {
        const normalizedName = normalizeText(name);
        const matchingRow = rows.find(row => getRowSearchValues(row).includes(normalizedName));

        if (matchingRow) {
            const targetCell = matchingRow.querySelectorAll('td')[1] || matchingRow;
            simulateClick(targetCell);
            found += 1;
            console.log('Clicked: ' + name);
            await new Promise(resolve => setTimeout(resolve, 300));
        } else {
            notFound.push(name);
            console.warn('Not found: ' + name);
        }
    }

    console.log('\nDone! ' + found + ' clicked for ' + selectionLabel + '. Not found: ' + (notFound.join(', ') || 'none'));
    return { found, notFound, selected: professorNames };
}

function selectProfessorsForSlot(dayCode, periodCode, explicitTable) {
    return selectProfessors(periodCode, dayCode, explicitTable);
}

function resetRun() {
    runCursor = 0;
    const queue = getRunQueue();
    console.log('Run cursor reset. Remaining scheduled slots: ' + queue.length + '.');
    return runCursor;
}

async function run(periodCode, dayCode, explicitTable) {
    if (typeof periodCode === 'string' && periodCode.trim()) {
        console.log('Running explicit slot: ' + formatRunLabel(normalizePeriod(periodCode), dayCode ? normalizeDay(dayCode) : null));
        return selectProfessors(periodCode, dayCode, explicitTable);
    }

    const queue = getRunQueue();

    if (queue.length === 0) {
        throw new Error('No scheduled slots found in click data.');
    }

    if (runCursor >= queue.length) {
        console.warn('All scheduled slots have already been processed. Run resetRun() to start again.');
        return null;
    }

    const nextEntry = queue[runCursor];
    const currentStep = runCursor + 1;

    console.log('Running slot ' + currentStep + '/' + queue.length + ': ' + formatRunLabel(nextEntry.period, nextEntry.day));

    const result = await selectProfessors(nextEntry.period, nextEntry.day, explicitTable);
    runCursor += 1;

    return {
        step: currentStep,
        total: queue.length,
        remaining: queue.length - runCursor,
        day: nextEntry.day,
        period: nextEntry.period,
        result,
    };
}

await loadClickData();

console.log('Ready. Run run() or run("T3", "TER").');
